[versions]
quarkus = "3.24.4"
drools = "8.44.2.Final"
jooq = "3.19.18"
spotless = "7.0.2"
spotbugs-plugin = "6.1.7"
testcontainers = "1.21.3"
dependency-check-plugin = "10.0.4"
lz4 = "1.8.0"
jackson-msgpack = "0.9.8"

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-rest = { module = "io.quarkus:quarkus-rest" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson" }
quarkus-jdbc-postgresql = { module = "io.quarkus:quarkus-jdbc-postgresql" }
quarkus-flyway = { module = "io.quarkus:quarkus-flyway" }
quarkus-smallrye-health = { module = "io.quarkus:quarkus-smallrye-health" }
quarkus-logging-json = { module = "io.quarkus:quarkus-logging-json" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
drools-engine = { module = "org.drools:drools-engine", version.ref = "drools" }
drools-mvel = { module = "org.drools:drools-mvel", version.ref = "drools" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5" }
rest-assured = { module = "io.rest-assured:rest-assured" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
lz4-java = { module = "org.lz4:lz4-java", version.ref = "lz4" }
jackson-dataformat-msgpack = { module = "org.msgpack:jackson-dataformat-msgpack", version.ref = "jackson-msgpack" }
quarkus-scheduler = { module = "io.quarkus:quarkus-scheduler" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependency-check-plugin" }
